### ISSUE TITLE
conda fails to create environment from yml

### ISSUE THREAD

**Issue by Dana162001** [klarman-cell-observatory/PowerAnalysisForSpatialOmics#2]
Hi, 
thank you for creating this fascinating method! I wanted to try it on my computer, but I got an error during installation process. Could you please suggest how can I solve it? 

Command that I used: (base) dana@Danas-MacBook-Air PowerAnalysisForSpatialOmics-master % conda env create -n ist --file env.yml

Anaconda error report: 
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/dana/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/Users/dana/anaconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/dana/anaconda3/lib/python3.9/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "/Users/dana/anaconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 103, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/Users/dana/anaconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 47, in detect
        if spec.can_handle():
      File "/Users/dana/anaconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 19, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/dana/anaconda3/lib/python3.9/site-packages/conda_env/env.py", line 169, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/dana/anaconda3/lib/python3.9/site-packages/conda_env/env.py", line 147, in from_yaml
        data = validate_keys(data, kwargs)
      File "/Users/dana/anaconda3/lib/python3.9/site-packages/conda_env/env.py", line 37, in validate_keys
        new_data = data.copy() if data else {}
    AttributeError: 'str' object has no attribute 'copy'

`$ /Users/dana/anaconda3/bin/conda-env create -n ist --file env.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/dana/anaconda3/bin/conda
             CONDA_PREFIX=/Users/dana/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/dana/anaconda3/bin/python
               CONDA_ROOT=/Users/dana/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/dana/anaconda3/bin:/Users/dana/anaconda3/condabin:/usr/local/bi
                          n:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run
                          /com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var
                          /run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/r
                          un/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinterna
                          l/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/dana/anaconda3
            shell level : 1
       user config file : /Users/dana/.condarc
 populated config files : /Users/dana/.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __osx=13.3=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/dana/anaconda3  (writable)
      conda av data dir : /Users/dana/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/dana/anaconda3/pkgs
                          /Users/dana/.conda/pkgs
       envs directories : /Users/dana/anaconda3/envs
                          /Users/dana/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Darwin/22.4.0 OSX/13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

My computer parameters: MacBook Air, Chip M2, Memory 8 GB, Startup disk Macintosh HD, macOS Ventura 13.3

Thank you in advance for your help!

**Comment by pakiessling** [comment]
@ethanagb I think the Issue is that the .yml looks more like a requirements.txt and is not valid yaml.
Could you upload the output of `conda env export > environment.yml`
Thank you!

**Comment by chiarasch** [comment]
See suggestion in https://github.com/klarman-cell-observatory/PowerAnalysisForSpatialOmics/issues/4, hope this helps!
